version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_ts_app_comments
    ports:
      - "3003:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db_comments
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
