name: Build and Push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build_image.outputs.image_tag }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image tag
        id: set_image_tag
        run: echo "IMAGE_TAG=my-image-name:$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        id: build_image
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/my-image-name:$(date +%s)"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_TAG }}
