name: Build and Push Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/comments-api/my-image-name:latest

      - name: Push the Docker image
        run: docker push ghcr.io/comments-api/my-image-name:latest
