name: Deploy Image

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization Step
        run: echo "Initializing deployment workflow."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull the Docker image
        run: docker pull ${{ env.IMAGE_TAG }}

      - name: Run the container
        run: docker run -d -p 3000:3000 ${{ env.IMAGE_TAG }}

      - name: Wait for the container to be ready
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost:3000/healthcheck; then
              echo "Container is ready!"
              exit 0
            fi
            echo "Waiting for container..."
            sleep 5
          done
          echo "Container did not become ready in time"
          exit 1

      - name: Run tests
        run: curl http://localhost:3000/healthcheck
