name: Build and Deploy with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for the container to be ready
        run: |
          for i in {1..20}; do
            if curl --fail http://localhost:3003/healthcheck; then
              echo "Container is ready!"
              exit 0
            fi
            echo "Waiting for container..."
            sleep 5
          done
          echo "Container did not become ready in time"
          exit 1

      - name: Run tests
        run: curl http://localhost:3003/healthcheck
